-- MULTI-TENANT ARCHITECTURE V2
-- DANGER: This script destructively wipes all old tables to map sequential numbering logic and User Isolation.

DROP TABLE IF EXISTS recurring CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS expenses CASCADE;
DROP TABLE IF EXISTS accounts CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS friends CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- 1. Users Gateway
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

-- 2. Friends Network
CREATE TABLE friends (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    linked_username TEXT REFERENCES users(username) ON DELETE SET NULL,
    active BOOLEAN DEFAULT TRUE
);

-- 3. Categories (Isolated)
CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    icon TEXT,
    type TEXT NOT NULL
);

-- 4. Accounts (Isolated)
CREATE TABLE accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    initial_balance NUMERIC DEFAULT 0.0,
    icon TEXT
);

-- 5. Splitwise Cross-Tenant Expenses 
-- Shared ledger bridging logic!
CREATE TABLE expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creator_username TEXT REFERENCES users(username) ON DELETE CASCADE, 
    description TEXT,
    amount NUMERIC NOT NULL,
    payer_username TEXT REFERENCES users(username) ON DELETE SET NULL, 
    participants JSONB NOT NULL, -- Format: { "username": {"amount": 250, "status": "pending"} }
    date TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Personal Transactions (Isolated)
CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    type TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
    account_id BIGINT REFERENCES accounts(id) ON DELETE CASCADE,
    description TEXT,
    date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    linked_split_id BIGINT
);

-- 7. Settlement Payments (Cross-Tenant)
CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_username TEXT REFERENCES users(username) ON DELETE CASCADE,
    to_username TEXT REFERENCES users(username) ON DELETE CASCADE,
    amount NUMERIC NOT NULL,
    status TEXT DEFAULT 'pending',
    date TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 8. Recurring Schemes (Isolated)
CREATE TABLE recurring (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    type TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
    account_id BIGINT REFERENCES accounts(id) ON DELETE CASCADE,
    description TEXT,
    frequency TEXT NOT NULL,
    next_date TIMESTAMP WITH TIME ZONE NOT NULL,
    active BOOLEAN DEFAULT TRUE
);
